version: '3.6'

services:
  db:
    container_name: db
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: fourcat
      POSTGRES_PASSWORD: supers3cr3t
      POSTGRES_DB: fourcat
      POSTGRES_HOST_AUTH_METHOD: trust
    volumes:
      - 4cat_data:/var/lib/postgresql/data/

  api:
    build: .
    container_name: api
    depends_on:
      - db
    environment:
      STAGE: test
      SQLALCHEMY_DATABASE_URI: postgresql+psycopg2://fourcat:supers3cr3t@db/fourcat
    networks:
      - default
    ports:
      - 5000:5000
    volumes:
      - ./app:/usr/src/app/app
      - ./migrations:/usr/src/app/migrations

volumes:
  4cat_data: {}