name: Docker Image CI

on:
  push:
    branches: docker-compose
  pull_request:
    branches: master
jobs  :
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the stack
        run: docker-compose up -d
      - name: Test
        run: curl -s --retry 10 --retry-connrefused http://localhost:5000/
