# This will keep the tag:latest up-to-date with all commits and pull requests

name: Publish Docker image tag:latest

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "master" ]
jobs:
  push_to_registry_amd64:
    name: Push Docker image to Docker Hub (amd64)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_DALE_LOGIN }}
          password: ${{ secrets.DOCKER_DALE_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: digitalmethodsinitiative/4cat

      - name: Build and push Docker image (amd64)
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64
          push: true
          tags: digitalmethodsinitiative/4cat:latest
        retry:
          max-attempts: 2
          delay-seconds: 30

  push_to_registry_arm64:
    name: Push Docker image to Docker Hub (arm64)
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_DALE_LOGIN }}
          password: ${{ secrets.DOCKER_DALE_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: digitalmethodsinitiative/4cat

      - name: Build and push Docker image (arm64)
        uses: docker/build-push-action@v6.13.0
        with:
          context: .
          file: docker/Dockerfile
          platforms: linux/arm64
          push: true
          tags: digitalmethodsinitiative/4cat:latest
        retry:
          max-attempts: 2
          delay-seconds: 30
